version: '3.8'

services:
  stockweb_django_app:
    image: stockweb:latest
    command: "python manage.py runserver 0.0.0.0:8000"
    container_name: stockwebapp
    volumes:
      - /home/pemadee/login_web/testenv/testproject:/app
    
    expose:
      - "8000"

    ports:
      - "8008:8000"