# Generated by Django 4.2.7 on 2023-11-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0006_borrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='logDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=225)),
                ('descri', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
